[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ~/.config/polybar/colors.ini

[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
bottom = true
fixed-center = true
width = 17%
height = 60
offset-x = 20
offset-y = 20
background = ${color.bg}
foreground = ${color.fg}
radius-top = 10.0
radius-bottom = 10.0
line-size = 2
line-color = ${color.ac}
border-bottom-size = 0
border-color = ${color.ac}
padding = 2
module-margin-left = 1
module-margin-right = 1
font-0 = "Iosevka Nerd Font:size=13;3"
font-1 = "Iosevka Nerd Font:bold:size=24;2"
font-2 = "Iosevka Nerd Font:size=22;6"
font-3 = "Source Code Pro:size=10;3"
font-5 = "Helvetica Rounded:style=Bold:size=10.5;3"
font-4 = "Montserrat Medium:style=Medium:size=12;3"
font-6 = "Hurmit Nerd Font Mono:style=medium:pixelsize=17;3"
font-7 = "fontello:style=Regular:pixelsize=25;3"

[bar/primary]
inherit = bar/main
offset-x = 96.9%
offset-y = 15
width = 2.5%
height = 25
bottom = false
padding = 0
module-margin-left = 0
module-margin-right = 0
background = ${color.bg}
foreground = ${color.g}
modules-center = sysmenu
wm-restack = bspwm

[bar/secondary]
inherit = bar/main
width = 8%
height = 25
offset-x = 4.3%
offset-y = 15
background = ${color.bg}
foreground = ${color.g}
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = date
wm-restack = bspwm

[bar/terciary]
inherit = bar/main
width = 12%
height = 25
offset-x = 12.5%
offset-y = 15
background = ${color.bg}
foreground = ${color.g}
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = ethernet_status
wm-restack = bspwm

[bar/quaternary]
inherit = bar/main
width = 12%
height = 25
offset-x = 24.8%
offset-y = 15
background = ${color.bg}
foreground = ${color.g}
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = htb_status
wm-restack = bspwm

[bar/quinary]
inherit = bar/main
width = 18%
height = 25
offset-x = 72.85%
offset-y = 15
background = ${color.bg}
foreground = ${color.g}
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = htb_target
wm-restack = bspwm

[bar/log]
inherit = bar/main
width = 3%
height = 25
offset-x = 1%
offset-y = 15
bottom = false
foreground = ${color.g}
background = ${color.bg}
padding = 0
modules-center = my-text-label
wm-restack = bspwm

[bar/top]
inherit = bar/main
width = 5.5%
height = 25
offset-x = 91.1%
offset-y = 15
bottom = false
font-0 = "Iosevka Nerd Font:size=12;3"
background = ${color.bg}
foreground = ${color.g}
padding = 1
module-margin-left = 1
module-margin-right = 1
modules-center = alsa battery

separator =
spacing = 0
dim-value = 1.0
wm-name = openbox
locale =
tray-position = none
tray-detached = false
tray-maxsize = 16
tray-transparent = false
tray-background = ${color.bg}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0
wm-restack = bspwm
enable-ipc = true
click-left =
click-middle =
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =
cursor-click =
cursor-scroll =

[settings]
throttle-output = 5
throttle-output-for = 10
throttle-input-for = 30
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
format-foreground = ${color.g}
format-background = ${color.bg}
format-underline =
format-overline =
format-spacing =
format-padding =
format-margin =
format-offset =
pseudo-transparency = false

[module/my-text-label]
type = custom/text
content = %{T7} 
format-foreground = ${color.g}
click-left = ~/.config/bin/theme-menu.sh

[module/date]
type = internal/date
interval = 1.0
time = %k : %M
date = %b %e
format = <label>
format-foreground = ${color.g}
label = %date%  |  %time% 
label-font = 6

[module/mpd]
type = internal/mpd
interval = 2
format-online = <label-song>
format-online-foreground = ${color.g}
label-song = "%title%"
label-song-maxlen = 12
label-song-ellipsis = true
label-offline = "Offline"

[module/term]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.g}
content-background = ${color.bg}
content-padding = 0
click-left  = termite &

[module/web]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.g}
content-background = ${color.bg}
content-padding = 0
click-left  = firefox &

[module/files]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.ac}
content-background = ${color.bg}
content-padding = 0
click-left  = thunar &

[module/edit]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.g}
content-background = ${color.bg}
content-padding = 0
click-left  = geany &

[module/apps]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.g}
content-background = ${color.bg}
content-padding = 0
click-left  = ~/.config/polybar/scripts/launcher &

[module/sep]
type = custom/text
content = " | "
content-font = 1
content-foreground = ${color.g}

[module/sep2]
type = custom/text
content = "   "
content-foreground = ${color.g}

[module/alsa]
type = internal/alsa
;format-background = ${color.z}
format-volume = <ramp-volume>
format-muted = <label-muted>
label-muted = %{A3:pavucontrol &:} 婢 %{A}
label-muted-foreground = ${color.gray}
;click-right = pavucontrol
ramp-volume-0 = %{A3:pavucontrol &:} 奄%{A}
ramp-volume-1 = %{A3:pavucontrol &:} 奔%{A}
ramp-volume-2 = %{A3:pavucontrol &:} 奔%{A}
ramp-volume-3 = %{A3:pavucontrol &:} 墳%{A}
ramp-volume-4 = %{A3:pavucontrol &:} 墳%{A}
ramp-volume-foreground = ${color.z}

[module/battery]
type = internal/battery

full-at = 99
battery = BAT1
adapter = ACAD

poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging>
format-discharging = <ramp-capacity>

format-full = <label-full>

format-full-foreground = ${color.g}

label-full = 

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
 
ramp-capacity-foreground = ${color.g}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 
animation-charging-7 = 
animation-charging-8 = 
animation-charging-9 = 

animation-charging-foreground = ${color.g}
animation-charging-framerate = 750

[module/wired-network]
type = internal/network
interface = eth1

[module/network]
type = internal/network
interface = ens33
click-left = kcmshell5 kcm_networkmanagement
interval = 1.0
accumulate-stats = true
unknown-as-up = true
format-connected = <label-connected>
format-connected-foreground = ${color.g}
format-disconnected = <label-disconnected>
format-disconnected-foreground = ${color.muted}
label-connected = 直
label-disconnected = 睊

[module/ethernet_status]
type = custom/script
interval = 2
exec = ~/.config/bin/htb_status.sh
click-left = ~/.config/bin/htb_status.sh --copy

[module/htb_status]
type = custom/script
interval = 2
exec = ~/.config/bin/htb_status.sh
click-left = ~/.config/bin/htb_status.sh --copy

[module/htb_target]
type = custom/script
interval = 2
exec = ~/.config/bin/htb_target.sh
click-left = ~/.config/bin/htb_target.sh --copy
[module/sysmenu]
type = custom/text  
content = 襤

;content-foreground = ${color.ac}
click-left = ~/.config/bin/powermenu.sh
